In [6]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import numpy as np

In [7]:
x = np.arange(10).reshape(-1, 1)
y = (2*x + 1).reshape(-1, 1)

In [8]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [10]:
y

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19]])

In [13]:
# 모델 선언
model = LinearRegression()

In [14]:
# 모델 학습
model.fit(x, y) #.fit(데이터(원값), 예측값)

LinearRegression()

In [21]:
# 예측
prediction = model.predict([[3]])
prediction

array([[7.]])